runtime: python39  # Using Python 3.9 runtime
entrypoint: python3 -m http.server 8080

handlers:
- url: /
  static_files: WAD1/index.html  # Specify the correct path
  upload: WAD1/index.html

- url: /(.*)
  static_files: WAD1/\1
  upload: WAD1/(.*)

